### ISSUE TITLE
Bundles not respecting enabled attribute

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-AssemblyLine#538]
**Describe the bug**
Bug introduced in https://github.com/SuffolkLITLab/docassemble-AssemblyLine/pull/531, document bundles don't look at their own `enabled` attribute anymore.

**To Reproduce**
1. Make a document bundle with one document:
```yaml
objects: 
  - my_bundle: ALDocumentBundle.using(title="hi", elements=[my_doc], ...)
---
objects:
  - my_doc: ALDocument.using(title="document", ...)
```
2. Disable the bundle, but enable the doc.
```yaml
code: |
  my_doc.enabled = True
  my_bundle.enabled = False
---
```
3. My bundle will still be enabled / show up if you do something like `my_bundle.download_html_list`, or put it in another bundle and do `that_bundle.download_html_list`. 

**Expected behavior**
The bundle should only be enabled if the bundle itself is enabled and it has enabled documents itself.

**Version Information (should be in `your.docassemble.server/updatepackage`:**
 - AssemblyLine Version: 2.13.0
