### ISSUE TITLE
Combobox Accessibility Issues

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-AssemblyLine#548]
Came across a use of a combo box in ILAO's Fee Waiver interview when doing an accessibility audit. There are a few accessibility issues I found when using it with a screen reader and keyboard:

* There is a button on the right side of the field that doesn't have any labels. Screen readers will announce it as just "Push button" or "button". I think the right way to describe it would be as a collapsible button, but...
* when you use keyboard controls to press the button, it quickly shows the available items, but then quickly selects the top option. What's actually happening is that on key down, the available items are shown, and then you can use the arrow keys to navigate and choose the right option, and on key up, that option is selected and entered into the combobox input field. This definitely isn't standard keyboard controls for a button like that (having to hold down one key while using others to choose something), and should be changed to be on 2 different key presses.
  * after writing this, I discovered that this only seems to happen on Firefox on Ubuntu, and not Firefox on windows, so I'm not sure how to start debugging OS differences here.
* the options available in the combobox aren't read out on the screen reader. With Orca (Ubuntu), nothing is read at all, and with NVDA (windows), it says "blank" each time you navigate to the next year selection.
* If you enter an invalid number and navigate to continue, the validation message pops up, but nothing is read out on with the reader (at all). If you navigate back to the combo box, it won't read out the issue either. If you just didn't enter anything it will read out "this field is required".

The combobox is a [separate bootstrap plugin](https://github.com/danielfarrell/bootstrap-combobox) that we would have to patch separately from docassemble. There haven't been any substantive merged PRs since 2019, so our best bet is to patch it ourselves, see if the author has the time to review and merge, and if not, convince Jonathan to use our branch instead.

Here's an image of what the combobox looks like, and some example code to try it out.

![Screenshot from 2022-08-05 15-22-45](https://user-images.githubusercontent.com/6252212/183146867-0563d49a-ad45-447f-88c4-052ff87657ff.png)

```yaml
question: |
  What year were you born?
fields:
  - Year of birth: birth_year
    input type: combobox
    datatype: integer
    maxlength: 4
    min: ${ today().year-120 }
    max: ${ today().year }
    code: |
      reversed(range(today().year-120, today().year+1))
```
