### ISSUE TITLE
Deprecate (remove) "no label" modifiers 

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLine#565]
"No label" doesn't play nicely with screen readers. We should rephrase screens so that every question has a label

**Comment by BryceStevenWilley** [comment]
Limited use case, but what works slightly better than no label is if it's the only field on the page is a dropdown, directly using a `choices` dropdown.

I do remember running into this and attempting an upstream fix for pages with just one field, but I don't remember if I gave it up for the above fix instead. There wasn't a great fix for `no label` though, but there just isn't as much information from the author, so I changed it to duplicate information already found on the page (and already read out by the screen reader), just associating it directly with the field.

**Comment by nonprofittechy** [comment]
@BryceStevenWilley are you saying that something like this:

```yaml
question: |
  Is anyone else on your side of the case?
field: users.there_is_another
choices:
  - Yes: True
  - No: False
```

Will be read correctly by the screen reader?
