### ISSUE TITLE
Discover the steps needed to migrate MAVC interview to AL

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#69]
As we migrate the first few interviews, add comments in here about what steps we each took to inform the next migrations and final instructions documentation.

Starting point is at https://github.com/suffolkLITLab/docassemble-assemblyline#migration:

> * Remove any references to MAVirtualCourt. Add an include block like this at the top
>   of your interview YAML file
> 
> ```
> include:
>   - docassemble.AssemblyLine:al_package.yml
>   - docassemble.MassAccess:massaccess.yml
> ```
> 
> * Change references to `basic_questions_intro_screen` to `al_intro_screen`

**Comment by nonprofittechy** [comment]
Replace any VCIndividual objects with ALIndividual objects

**Comment by plocket** [comment]
This is what I've come up with, though I have a couple questions and I'm not sure everything I've labeled as optional is actually optional and visa versa. For a clear diff between an old form and a new form, see [this commit on 209A Plaintiff Motion to Modify](https://github.com/SuffolkLITLab/docassemble-209aPlaintiffMotionToModify/commit/bd67f9fdbd6547aeb48bd845fdb9ac33fdde2c4e).

### General
- [ ] Change the `include` block to:
``` yml
---
include:
  - docassemble.AssemblyLine:al_package.yml
  - docassemble.MassAccess:massaccess.yml
---
```
- [ ] Create your own objects block for people based on your needs. The below will ask for exactly one user and one other party. TODO: Add documentation about the different ways to ask for different amounts of possible people.
```yml
---
objects:
  - users: ALPeopleList.using( target_number=1, ask_number=True )
  - other_parties: ALPeopleList.using( target_number=1, ask_number=True )
---
```
- [ ] If you have your own question for choosing a court change the `choices` value from using `macourts` to using `all_courts`:
```
choices: all_courts.filter_courts(allowed_courts)
```
- [ ] (optional) Change `courts[0]` to `trial_court`

### Update attachments to ALDocument
Is it optional to convert to ALDocument?

- [ ] Remove the blocks defining `form_to_sign` and `form_to_file_no_cover`.
- [ ] When you need to display the form in the preview, use `${ al_user_bundle.as_pdf( key='preview' ) }` instead of `form_to_sign`.
- [ ] Remove other appearances of those two variables
- [ ] Remove `attachment code:` from the download screen
- [ ] Define your ALDocuments and ALBundles. Use the correct file names for your interview. I'm not sure where the template file name goes vs. the name shown to the user. Make sure to do it in two separate blocks:
```yml
---
objects:
  - al_court_bundle: ALDocumentBundle.using(elements=[attachment_var_name], filename="filename-court-will-see.pdf", title="All forms to send to the court")
  - al_user_bundle: ALDocumentBundle.using(elements=[attachment_var_name], filename="filename-user-will-see.pdf", title="Form to download")
---
objects:
  - attachment_var_name: ALDocument.using( enabled=True, has_addendum=False, title='Display Name of Form', filename='filename-human-will-see.pdf' )
---
```
[Halp: I'm concerned I've made an error in the repo here: https://github.com/SuffolkLITLab/docassemble-209aPlaintiffMotionToModify/commit/bd67f9fdbd6547aeb48bd845fdb9ac33fdde2c4e#diff-221941e601213702410f2e2f937dc7f0161f7af6f127393555a11cdc044a540aR365-R370. Not sure which bit is supposed to reference the actual template file name and which is just the name the file will have when it's given to the user. It's not clear to me from the documentation.]

Your ALDocumentBundle and ALDocument objects' attributes may need to be a little different. You can see the documentation for those objects in this file: https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/main/docassemble/AssemblyLine/al_document.py

- [ ] Add these lines to the bottom of your download screen. Make sure to use the name of your own bundles:
```yml
  ${ al_user_bundle.download_list_html( key='final' ) }
  
  ${ al_user_bundle.send_button_html( key='final' ) }
```
- [ ] Remove the preview attachment block
- [ ] In the other attachment block, add `[i]` to the end of the `variable name:`. E.g:
```yml
attachment:
    variable name: plaintiff_modify_209A_attachment[i]
```
- [ ] In that same attachment block, remove the line with the `name:` specifier
- [ ] In that same attachment block, remove the line with the `filename:` specifier
- [ ] Replace `users[0].signature` with `users[0].signature_if_final( i )`

### Dependencies
(optional)
- [ ] (optional) On your Package page, make sure in your list of dependencies, `docassemble.MAVirtualCourt` is no longer selected
- [ ] (optional) Make sure these are selected
   - [ ] `docassemble.ALMassachusetts`
   - [ ] `docassemble.ALToolbox`
   - [ ] `docassemble.AssemblyLine`
   - [ ] `docassemble.MACourts`
   - [ ] `docassemble.MassAccess`

### Optional
- [ ] (optional?) Use `al_intro_screen` instead of `basic_questions_intro_screen`
- [ ] (optional) Remove any custom question about signing under oath. The AL package has one now.
- [ ] (optional) If you're using `users[0].name.first`, use `people_list_of_some_kind.gather()` instead (even if you have only one of the type of person). Remove code after that refers to things like `people_list_of_some_kind.gathered`, `people_list_of_some_kind.there_is_another`, `people_list_of_some_kind.ask_number`, and `people_list_of_some_kind.target_number`.
- [ ] (optional) For custom-built name questions, use `.name_fields()` and the `sets` specifier. E.g:
```yml
---
id: defendant name
sets:
  - other_parties[0].name.first
  - other_parties[0].name.last
question:  |
  What is the defendant's name?
fields:
  - code: |
      other_parties[0].name_fields()
---
```

That's what I was able to gather just from the diff. It may actually be more clear for folks to just look at the diff, but whatever helps is good 👍
