### ISSUE TITLE
names of opposing parties: Allow dev to set person type for each individual

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#92]
Allow dev to set person type (business or person) for each individual that may be asked their name. Regarding this line in the code:

https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/4dd5e94e1ee256527ace6b8f7c799a5e81712d99/docassemble/AssemblyLine/data/questions/ql_baseline.yml#L495

One option:
```yml
# AL Developers: To override this value, copy this block into your file and
# change 'unsure' to either 'person' or 'business'.
generic object: ALIndividual
code: |
  x.person_type = 'unsure'
---
#...
       other_parties[i].name_fields(person_or_business=other_parties[i].person_type)
```
