### ISSUE TITLE
ALPeopleList `foo.gather()` causes 'can't find i' error.

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#95]
Code to reproduce:
```yml
include:
  - docassemble.AssemblyLine:al_package.yml
  - docassemble.MassAccess:massaccess.yml
---
objects:
  - people: ALPeopleList.using(ask_number=True, target_number=1)
---
mandatory: True
code: |
  people.gather()
---
```

Error: `There was a reference to a variable 'i' that could not be looked up in the question file`

Variable sought: `people[0].name.first`

My guess is that lines 498 and 499 need to reference `x[i]` instead of `x[0]`.
https://github.com/SuffolkLITLab/docassemble-AssemblyLine/blob/681d389d98d0455d53064eae2221025f0c1fb2ab/docassemble/AssemblyLine/data/questions/ql_baseline.yml#L496-L509
